= 또잇또잇 BE_API
:doctype: book
:icons: font
:source-highlighter: highlightjs
==
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

== 아래에 adoc을 정의하면 됩니다.

[[overview]]
== Overview

[[overview-http-status-codes]]
=== HTTP status codes

|===
| 상태 코드 | 설명

| `200 OK`
| 성공

| `400 Bad Request`
| 잘못된 요청

| `401 Unauthorized`
| 비인증 상태

| `403 Forbidden`
| 권한 거부

| `404 Not Found`
| 존재하지 않는 요청 리소스

| `500 Internal Server Error`
| 서버 에러
|===

[[overview-error-response]]
=== HTTP Error Response
operation::common-doc-controller-test/error-sample[snippets='http-response,response-fields']

== Store API

[[get-store]]
=== 1. 핀 클릭시 음식점 바텀시트 조회
operation::store-controller-test/get-store[]

[[get-store-report]]
=== 2. 또잇 리포트 및 음식점 상세 페이지 상단 이미지
operation::store-controller-test/get-store-report[]

[[get-store-list]]
=== 3. 리뷰 조회
operation::store-controller-test/get-store-review[]

[[create-exist-store-review]]
=== 4-1. 리뷰 작성 (기존에 존재하는 가게)
operation::store-controller-test/create-exist-store-review[]

[[create-new-store-review]]
=== 4-2. 리뷰 작성 (새로운 가게)
operation::store-controller-test/create-new-store-review[]

== User API

=== 1. 유저 닉네임 변경
operation::user-controller-test/get-my-reviews[]

=== 2. 유저 프로필 조회
operation::user-controller-test/get-my-reviews[]

=== 3. 유저 북마크 조회
operation::user-controller-test/get-my-bookmarks[]

=== 4. 유저 리뷰 조회
operation::user-controller-test/get-my-reviews[]


== Store Search API

[[get-store-search]]
=== 음식점, 카페 통합 검색
operation::store-search-controller-test/search[]


== Test API

[[test-api-create]]
=== Create a test
operation::test-controller-test/create[]

[[test-api-findById]]
=== Find a test by ID
operation::test-controller-test/find-by-id[snippets='curl-request,http-request,http-response,httpie-request,path-parameters,request-headers,response-body,response-fields']

[[test-api-findByTitle]]

[[test-api-findAll]]
=== Find all
operation::test-controller-test/find-all[]

[[test-api-update]]
=== Update
operation::test-controller-test/update[]

[[test-api-delete]]
=== Delete
operation::test-controller-test/delete[]

[[test-api-enum]]
=== enums
operation::test-controller-test/enum-test[]
