= 또잇또잇 BE_API
:doctype: book
:icons: font
:source-highlighter: highlightjs
==
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

[[overview]]
== Overview

[[overview-http-status-codes]]
=== HTTP status codes

|===
| 상태 코드 | 설명

| `200 OK`
| 성공

| `400 Bad Request`
| 잘못된 요청

| `401 Unauthorized`
| 비인증 상태

| `403 Forbidden`
| 권한 거부

| `404 Not Found`
| 존재하지 않는 요청 리소스

| `500 Internal Server Error`
| 서버 에러
|===

[[overview-error-response]]
=== HTTP Error Response
operation::common-doc-controller-test/error-sample[snippets='http-response,response-fields']

== Auth API
[[login]]
=== 1. 로그인

operation::auth-controller-test/social-login[snippets='curl-request,http-request,query-parameters,http-response']

[[signup]]
=== 2. 약관동의 후 회원가입

operation::auth-controller-test/signup[snippets='curl-request,http-request,request-headers,http-response']

[[refresh-token]]
=== 3. 토큰 재발급
* refresh token으로 access token을 재발급합니다.

operation::auth-controller-test/refresh-token[snippets='curl-request,http-request,request-headers,http-response']

[[logout]]
=== 4. 로그아웃

operation::auth-controller-test/logout[snippets='curl-request,http-request,http-response']

== Store API

[[get-store]]
=== 1. 핀 클릭시 음식점 바텀시트 조회
operation::store-controller-test/get-store[]

[[get-store-report]]
=== 2. 또잇 리포트 및 음식점 상세 페이지 상단 이미지
operation::store-controller-test/get-store-report[]

[[get-store-list]]
=== 3. 리뷰 조회
operation::store-controller-test/get-store-review[]

[[create-exist-store-review]]
=== 4-1. 리뷰 작성 (기존에 존재하는 가게)
operation::store-controller-test/create-exist-store-review[]

[[create-new-store-review]]
=== 4-2. 리뷰 작성 (새로운 가게)
operation::store-controller-test/create-new-store-review[]

[[delete-review]]
=== 5. 리뷰 삭제(본인이 작성한 리뷰만)
operation::store-controller-test/delete-review[]

[[create-bookmark]]
=== 6. 북마크 등록 및 삭제
operation::bookmark-controller-test/update-bookmark[]

[[get-location-range-stores]]
=== 7. 지도에서 위,경도 내에 존재하는 식당정보 조회
operation::store-controller-test/get-location-range-stores[]

[[get-user-daily-store-review-limit]]
=== 8. 사용자 리뷰 작성 가능 여부 체크
operation::store-controller-test/get-user-daily-store-review-limit[]

== User API

=== 1. 유저 닉네임 변경
operation::user-controller-test/update-user-nickname[]

=== 2. 유저 프로필 조회
operation::user-controller-test/get-user-profile[]

=== 3. 유저 북마크 조회
operation::user-controller-test/get-my-bookmarks[]

=== 4. 유저 리뷰 조회
operation::user-controller-test/get-my-reviews[]

=== 5. 회원 탈퇴
operation::user-controller-test/delete-user-test[snippets='curl-request,http-request,http-response']

== Store Search API

[[get-store-search]]
=== 음식점, 카페 통합 검색
operation::store-search-controller-test/search[]

== Image API
=== presigned url 발급
operation::image-controller-test/get-presigned-url[snippets='curl-request,http-request,http-response,query-parameters,request-headers,response-fields']

== Test API

[[test-token]]
=== 1. 테스트용 토큰 발급
operation::auth-controller-test/get-test-token[]
