= 또잇또잇 BE_API
:doctype: book
:icons: font
:source-highlighter: highlightjs
==
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

[[overview]]
== Overview

[[overview-http-status-codes]]
=== HTTP status codes

|===
| 상태 코드 | 설명

| `200 OK`
| 성공

| `400 Bad Request`
| 잘못된 요청

| `401 Unauthorized`
| 비인증 상태

| `403 Forbidden`
| 권한 거부

| `404 Not Found`
| 존재하지 않는 요청 리소스

| `500 Internal Server Error`
| 서버 에러
|===

[[overview-error-response]]
=== HTTP Error Response
operation::common-doc-controller-test/error-sample[snippets='http-response,response-fields']

== Auth API
[[login]]
=== 1. 로그인
* "accessToken", "refreshToken"으로 쿠키에 토큰 담아 반환

Request
[source,http]
----
GET /oauth2/authorization/{provider}?env=local HTTP/1.1
Host: localhost:8080
Content-Type: application/json;charset=UTF-8
----
Path Parameter
[cols="1,2,3", options="header"]
|===
| Parameter
| Description
| Example Values

| provider
| 소셜로그인 종류
| apple, kakao

|===

Query Parameter
[cols="1,2,3", options="header"]
|===
| Parameter
| Description
| Example Values

| env
| 프론트 요청 환경
| local, dev (쿼리 스트링 없이 보낸 경우 dev로 리다이렉트 됩니다)

|===

[[signup]]
=== 2. 약관동의 후 회원가입
* 리다이렉트 쿼리스트링으로 "accessToken", "refreshToken" 반환

operation::auth-controller-test/signup[snippets='curl-request,http-request,request-headers,http-response']

[[refresh-token]]
=== 3. 토큰 재발급
* refresh token으로 access token을 재발급합니다.

operation::auth-controller-test/refresh-token[snippets='curl-request,http-request,request-headers,http-response']

== Store API

[[get-store]]
=== 1. 핀 클릭시 음식점 바텀시트 조회
operation::store-controller-test/get-store[]

[[get-store-report]]
=== 2. 또잇 리포트 및 음식점 상세 페이지 상단 이미지
operation::store-controller-test/get-store-report[]

[[get-store-list]]
=== 3. 리뷰 조회
operation::store-controller-test/get-store-review[]

[[create-exist-store-review]]
=== 4-1. 리뷰 작성 (기존에 존재하는 가게)
operation::store-controller-test/create-exist-store-review[]

[[create-new-store-review]]
=== 4-2. 리뷰 작성 (새로운 가게)
operation::store-controller-test/create-new-store-review[]

[[delete-review]]
=== 4-3. 리뷰 삭제(본인이 작성한 리뷰만)
operation::store-controller-test/delete-store-review[]

[[create-bookmark]]
=== 5-1. 북마크 등록
operation::bookmark-controller-test/create-bookmark[]

[[delete-bookmark]]
=== 5.2 북마크 삭제
operation::bookmark-controller-test/delete-bookmark[]

[[get-location-range-stores]]
=== 6. 지도에서 위,경도 내에 존재하는 식당정보 조회
operation::store-controller-test/get-location-range-stores[]

[[get-user-daily-store-review-limit]]
=== 7. 사용자 리뷰 작성 가능 여부 체크
operation::store-controller-test/get-user-daily-store-review-limit[]

== User API

=== 1. 유저 닉네임 변경
operation::user-controller-test/update-user-nickname[]

=== 2. 유저 프로필 조회
operation::user-controller-test/get-user-profile[]

=== 3. 유저 북마크 조회
operation::user-controller-test/get-my-bookmarks[]

=== 4. 유저 리뷰 조회
operation::user-controller-test/get-my-reviews[]


== Store Search API

[[get-store-search]]
=== 음식점, 카페 통합 검색
operation::store-search-controller-test/search[]

== Image API
=== presigned url 발급
operation::image-controller-test/get-presigned-url[snippets='curl-request,http-request,http-response,query-parameters,request-headers,response-fields']

== Test API

[[test-token]]
=== 1. 테스트용 토큰 발급
operation::auth-controller-test/get-test-token[]
