### 테스트 토큰 발급
GET {{host}}/api/v1/auth/access-token/1

### 맵에서 식당 정보 조회
GET {{host}}/api/v1/stores/location-range?latitude1=35.0000&longitude1=120.000&latitude2=50.000&longitude2=135.000&level=1
#GET {{host}}/api/v1/stores/location-range?latitude1=35.0000&longitude1=120.000&latitude2=50.000&longitude2=135.000&level=1&type=KOREAN
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}
