### 맵에서 식당 정보 조회
GET {{host}}/api/v1/stores/location-range?leftTopLatitude=50.000&leftTopLongitude=120.000&rightBottomLatitude=35.0000&rightBottomLongitude=150.000&level=1&type=CHINESE
#GET {{host}}/api/v1/stores/location-range?latitude1=35.0000&longitude1=120.000&latitude2=50.000&longitude2=135.000&level=1&type=KOREAN
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

### 나의 재방문한 식당 공유하기
GET {{host}}/api/v1/stores/sharing-spot
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

### 식당 상세 페이지에서 리뷰 조회(페이징)
GET {{host}}/api/v1/stores/1/reviews?type=&page=1
#GET {{host}}/api/v1/stores/1/reviews?type=REVISITED&page=1
#GET {{host}}/api/v1/stores/1/reviews?type=PHOTO&page=1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

### 음식점, 카페 통합 검색
GET {{host}}/api/v1/stores/search?query=떡볶이&x=127.06283102249932&y=37.514322572335935&storePage=1&cafePage=1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

### 리뷰 삭제(본인이 작성한)
DELETE {{host}}/api/v1/reviews/1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

### 공유하기
GET {{host}}/api/v1/stores/sharing-spot?userId=71
Content-Type: application/json;charset=UTF-8
